services:
  db:
    image: postgres:17
    ports:
      # Expose Postgres on the host (optional â€“ you can remove this if you don't need direct DB access)
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.prod

  django-web:
    build: ./backend
    container_name: django-docker
    depends_on:
      - db
    volumes:
      - ./backend/static:/app/staticfiles
    env_file:
      - ./backend/.env.prod

  backend-proxy:
    image: nginx:latest
    ports:
      # Host port 8003 -> container port 80
      - "8003:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static:/static:ro
    depends_on:
      - django-web

  frontend:
    build: ./frontend
    container_name: registration-frontend
    ports:
      # Host port 3003 -> container port 3000 (from frontend Dockerfile)
      - "3003:3000"
    env_file:
      - ./frontend/.env

volumes:
  postgres_data:


